<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>comment</key>
	<string>SCSS</string>
	<key>fileTypes</key>
	<array>
		<string>scss</string>
	</array>
	<key>name</key>
	<string>SCSS</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#variable-declaration</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#at-rule_include</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#at-rule_import</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#general</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#flow</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#rules</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#property-list</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#at-rule_mixin-function</string>
		</dict>
		<dict>
			<key>include</key>
			<string>source.css#at-rule_font-face</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#at-rule_media</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#at-rule_namespace</string>
		</dict>
		<dict>
			<key>include</key>
			<string>source.css#at-rule_page</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#at-rule_charset</string>
		</dict>
		<dict>
			<key>include</key>
			<string>source.css#at-rule_viewport</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>at-rule_charset</key>
		<dict>
			<key>begin</key>
			<string>\s*(@charset)\s*</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.at-rule.css</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Repeated because strings can contain variables in SCSS</string>
			<key>end</key>
			<string>(?=&lt;/style&gt;)|\s*(;|(?=\}))</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.terminator.rule.css</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.at-rule.charset.css</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#string_double</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string_single</string>
				</dict>
			</array>
		</dict>
		<key>at-rule_debug-warn</key>
		<dict>
			<key>begin</key>
			<string>\s*(@(?:debug|warn))\s*</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.at-rule.scss</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=&lt;/style&gt;)|\s*(;|(?=\}))</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.terminator.rule.scss</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.at-rule.debug-warn.scss</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#variables</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string_double</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string_single</string>
				</dict>
			</array>
		</dict>
		<key>at-rule_each</key>
		<dict>
			<key>begin</key>
			<string>\s*(@each)\s*</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.at-rule.scss</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=&lt;/style&gt;|\{)</string>
			<key>name</key>
			<string>meta.at-rule.each.scss</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.css#comment_block</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment_line</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(in)\b</string>
					<key>name</key>
					<string>keyword.control.operator.scss</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#variables</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#property-values</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.css#comma</string>
				</dict>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<key>at-rule_extend</key>
		<dict>
			<key>begin</key>
			<string>\s*(@extend)\s*</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.at-rule.scss</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=&lt;/style&gt;)|\s*(;|(?=\}))</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.terminator.rule.scss</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.at-rule.extend.scss</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#variables</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#selectors</string>
				</dict>
			</array>
		</dict>
		<key>at-rule_for</key>
		<dict>
			<key>begin</key>
			<string>\s*(@for)\s*</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.at-rule.scss</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=&lt;/style&gt;|\{)</string>
			<key>name</key>
			<string>meta.at-rule.for.scss</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.css#comment_block</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment_line</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(\=\=|\!\=|\&lt;\=|\&gt;\=|\&lt;|\&gt;|from|through)</string>
					<key>name</key>
					<string>keyword.control.operator.scss</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#variables</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#property-values</string>
				</dict>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<key>at-rule_if-else</key>
		<dict>
			<key>begin</key>
			<string>\s*(@(if|else))\s*</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.at-rule.scss</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\s*(?=&lt;/style&gt;|\{)</string>
			<key>name</key>
			<string>meta.at-rule.if-else.scss</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#logical-operators</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#variables</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#property-values</string>
				</dict>
			</array>
		</dict>
		<key>at-rule_import</key>
		<dict>
			<key>begin</key>
			<string>\s*(@import)\s*</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.at-rule.css</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=&lt;/style&gt;)|\s*(;|(?=\}))</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.terminator.rule.css</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.at-rule.import.css</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?&lt;=@import)\s+(?:((?:mso|-(?:ah|atsc|hp|khtml|moz|ms|ro|o|prince|rim|tc|wap|webkit|[\w\-]+))-[\w\-]+)|(url)|(abs|adjust-color|adjust-hue|alpha|blue|ceil|change-color|comparable|complement|darken|desaturate|fade-out|floor|grayscale|green|hue|if|invert|join|length|lighten|lightness|mix|nth|opacify|opacity|percentage|quote|red|round|saturate|saturation|scale-color|transparentize|type-of|unitless|unit|unquote)|([[:alpha:]](?:[-\w]+)?))\s*(\()</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.function.vendor.css</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.function.css</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>support.function.scss</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>support.function.misc.scss</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.function.css</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>This copies #function exactly except it checks for the presence of an @import immediately before it so it does not interfere with media features. These do not work in SCSS yet, but if SCSS intends on remaining compatible with CSS it needs to support CSS3 media queries in @import.</string>
					<key>end</key>
					<string>\)</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.function.css</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.function.css</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.css#parameters</string>
						</dict>
						<dict>
							<key>include</key>
							<string>source.css#function</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>source.css#comment_block</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string_single</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string_double</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.css#media_type</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.css#media_feature</string>
				</dict>
			</array>
		</dict>
		<key>at-rule_include</key>
		<dict>
			<key>begin</key>
			<string>\s*(@include)\s*</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.at-rule.scss</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=&lt;/style&gt;)|\s*(;|(?=\}))</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.terminator.rule.scss</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.at-rule.include.scss</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#function</string>
				</dict>
			</array>
		</dict>
		<key>at-rule_media</key>
		<dict>
			<key>begin</key>
			<string>\s*(@media)\s*</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.at-rule.scss</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=&lt;/style&gt;|\{)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string></string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.at-rule.media.scss</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.css#comment_block</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment_line</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.css#media_type</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#media_feature</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.css#media_and</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.css#comma</string>
				</dict>
			</array>
		</dict>
		<key>at-rule_mixin-function</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\s*(@(?:mixin|function))\s+([\w\-_]+)\s*</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.at-rule.scss</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.scss</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>With attributes</string>
					<key>end</key>
					<string>\s*(?=&lt;/style&gt;|\{)</string>
					<key>name</key>
					<string>meta.at-rule.mixin-function.scss</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.css#comment_block</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#comment_line</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>\s*(\()\s*</string>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.keyword.scss</string>
								</dict>
							</dict>
							<key>end</key>
							<string>\s*(\))\s*</string>
							<key>name</key>
							<string>meta.at-rule.mixin-function-attributes.scss</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#function_attributes</string>
								</dict>
							</array>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>at-rule_namespace</key>
		<dict>
			<key>begin</key>
			<string>\s*(@namespace)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.at-rule.css</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Repeated because strings can contain variables in SCSS</string>
			<key>end</key>
			<string>(?=&lt;/style&gt;)|\s*(;)</string>
			<key>name</key>
			<string>meta.at-rule.namespace.css</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?&lt;=@namespace)\s+([-\w]+)\s*</string>
					<key>name</key>
					<string>constant.namespace.prefix.css</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#general</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string_single</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string_double</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#function</string>
				</dict>
			</array>
		</dict>
		<key>at-rule_return</key>
		<dict>
			<key>begin</key>
			<string>\s*(@return)\s*</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.at-rule.scss</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=&lt;/style&gt;)|\s*(;|(?=\}))</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.terminator.rule.scss</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.at-rule.return.scss</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#general</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#property-values</string>
				</dict>
			</array>
		</dict>
		<key>at-rule_while</key>
		<dict>
			<key>begin</key>
			<string>\s*(@while)\s*</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.at-rule.scss</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\s*(?=&lt;/style&gt;|\{)</string>
			<key>name</key>
			<string>meta.at-rule.while.scss</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.css#comment_block</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment_line</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#logical-operators</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#variables</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#property-values</string>
				</dict>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<key>comment_line</key>
		<dict>
			<key>begin</key>
			<string>//</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.scss</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\s*(?=&lt;/style)|\n</string>
			<key>name</key>
			<string>comment.line.scss</string>
		</dict>
		<key>flow</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#at-rule_debug-warn</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#at-rule_if-else</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#at-rule_for</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#at-rule_while</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#at-rule_each</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#at-rule_return</string>
				</dict>
			</array>
		</dict>
		<key>function</key>
		<dict>
			<key>begin</key>
			<string>(?:((?:mso|-(?:ah|atsc|hp|khtml|moz|ms|ro|o|prince|rim|tc|wap|webkit|[\w-]+))-[\w-]+)|(calc|counter|cubic-bezier|cycle|hsla|hsl|image|local|matrix3d|matrix|perspective|radial-gradient|repeating-linear-gradient|linear-gradient|repeating-radial-gradient|rgba|rgb|rotate3d|rotateX|rotateY|rotateZ|rotate|scale3d|scaleX|scaleY|scaleZ|scale|skewX|skewY|steps|translate3d|translateX|translateY|translateZ|translate|url)|(abs|adjust-color|adjust-hue|alpha|blue|ceil|change-color|comparable|complement|darken|desaturate|fade-out|floor|grayscale|green|hue|if|invert|join|length|lighten|lightness|mix|nth|opacify|opacity|percentage|quote|red|round|saturate|saturation|scale-color|transparentize|type-of|unitless|unit|unquote)|([[:alpha:]](?:[-\w]+)?))\s*(\()</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.vendor.css</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.function.css</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>support.function.scss</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>support.function.misc.scss</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.function.scss</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\)</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.function.scss</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.function.scss</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#parameters</string>
				</dict>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<key>function_attributes</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>:</string>
					<key>name</key>
					<string>punctuation.definition.scss</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#general</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#property-values</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[=\{\}\?\;\@]</string>
					<key>name</key>
					<string>invalid.illegal.scss</string>
				</dict>
			</array>
		</dict>
		<key>general</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#variables</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.css#comment_block</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment_line</string>
				</dict>
			</array>
		</dict>
		<key>interpolation</key>
		<dict>
			<key>begin</key>
			<string>#\{</string>
			<key>end</key>
			<string>\}</string>
			<key>name</key>
			<string>variable.interpolation.scss</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#property-values</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#variables</string>
				</dict>
			</array>
		</dict>
		<key>logical-operators</key>
		<dict>
			<key>match</key>
			<string>(\=\=|\!\=|\&lt;\=|\&gt;\=|\&lt;|\&gt;|not|or|and)</string>
			<key>name</key>
			<string>keyword.control.operator</string>
		</dict>
		<key>media_feature</key>
		<dict>
			<key>begin</key>
			<string>\s*(\()\s*</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.at-rule.media.feature.css</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Repeated because media features can contain variables in SCSS</string>
			<key>end</key>
			<string>\s*(\))\s*</string>
			<key>name</key>
			<string>meta.at-rule.media.feature.css</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#variables</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(:)\s*</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.key-value.css</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\s*(?=\s*\))</string>
					<key>name</key>
					<string>meta.property-value.at-rule.media.css</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\/</string>
							<key>name</key>
							<string>punctuation.separator.ratio.css</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#property-values</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.key-value.css</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>For when a variable is used as a property value. Highlights the abandoned colon.</string>
					<key>match</key>
					<string>(:)\s*</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.css#property-name</string>
				</dict>
			</array>
		</dict>
		<key>parameters</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#general</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#property-values</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.css#string_unquoted</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.css#comma</string>
				</dict>
			</array>
		</dict>
		<key>properties</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?&lt;![-a-z])(?=[-a-z])</string>
					<key>end</key>
					<string>$|(?![-a-z])</string>
					<key>name</key>
					<string>meta.property-name.scss</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.css#property-name</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#at-rule_include</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(:)\s*(?!(\s*\{))</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.key-value.scss</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\s*(;|(?=\}))</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.terminator.rule.scss</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.property-value.scss</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#general</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#property-values</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>property-list</key>
		<dict>
			<key>begin</key>
			<string>\{</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.property-list.scss</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\s*(?=&lt;/style)|\}</string>
			<key>name</key>
			<string>meta.property-list.scss</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#flow</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#rules</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#properties</string>
				</dict>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<key>property-values</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#string_single</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string_double</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#function</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.css#value_important</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#value_unit</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.css#value_color</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.css#value_property-value</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.css#value_color-constant</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.css#value_number</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.css#value_font</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.css#value_operators</string>
				</dict>
			</array>
		</dict>
		<key>rules</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#general</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#at-rule_extend</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#at-rule_include</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#selectors</string>
				</dict>
			</array>
		</dict>
		<key>selector_attribute</key>
		<dict>
			<key>begin</key>
			<string>(\[)\s*([\w]+)\s*((\~|\^|\$|\*|\|)?\=)?\s*</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.attribute-selector.begin.css</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.other.attribute-name.css</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.attribute-selector.css</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Repeated because strings can contain variables in SCSS</string>
			<key>end</key>
			<string>\s*(?=&lt;/style)|(\])</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.attribute-selector.end.css</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#string_single</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string_double</string>
				</dict>
			</array>
		</dict>
		<key>selector_parent</key>
		<dict>
			<key>match</key>
			<string>\&amp;</string>
			<key>name</key>
			<string>entity.name.tag.reference.scss</string>
		</dict>
		<key>selector_pseudo-class-selector</key>
		<dict>
			<key>begin</key>
			<string>(\:not)\s*(\()</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.pseudo-class.css</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.pseudo-class.css</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Pseudo-classes containing selectors.</string>
			<key>end</key>
			<string>(\))\s*</string>
			<key>endCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.pseudo-class.css</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.pseudo-class.css</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#variables</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#selectors</string>
				</dict>
			</array>
		</dict>
		<key>selector_pseudo-class-string</key>
		<dict>
			<key>begin</key>
			<string>(\:lang)\s*(\()</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.pseudo-class.css</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.pseudo-class.css</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Pseudo-classes containing strings.</string>
			<key>end</key>
			<string>(\))\s*</string>
			<key>endCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.pseudo-class.css</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.pseudo-class.css</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#variables</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string_double</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string_single</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.css#string_unquoted</string>
				</dict>
			</array>
		</dict>
		<key>selector_pseudo-class-structural</key>
		<dict>
			<key>begin</key>
			<string>(\:(?:first-of-type|last-of-type|nth-child|nth-last-child|nth-last-of-type|nth-of-type|only-of-type))\s*(\()</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.pseudo-class.css</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.pseudo-class.css</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Pseudo-classes containing structural calculations.</string>
			<key>end</key>
			<string>(\))\s*</string>
			<key>endCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.pseudo-class.css</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.pseudo-class.css</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#variables</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.css#value_number</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.css#value_operators</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.structure-calculation.pseudo-class.css</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\s*(n)\s*</string>
				</dict>
			</array>
		</dict>
		<key>selectors</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.css#selector_namespace</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.css#selector_type</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.css#selector_class</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.css#selector_id</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.css#selector_pseudo-class</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#selector_pseudo-class-selector</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#selector_pseudo-class-string</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#selector_pseudo-class-structural</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.css#selector_universal</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#selector_parent</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.css#selector_pseudo-element</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#selector_attribute</string>
				</dict>
			</array>
		</dict>
		<key>string_double</key>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.css</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.css</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.css</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.css</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#variables</string>
				</dict>
			</array>
		</dict>
		<key>string_single</key>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.css</string>
				</dict>
			</dict>
			<key>end</key>
			<string>'</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.css</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.single.css</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.css</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#variables</string>
				</dict>
			</array>
		</dict>
		<key>value_unit</key>
		<dict>
			<key>comment</key>
			<string>The } in the lookbehind is for interpolation.</string>
			<key>match</key>
			<string>(?&lt;=[\d]|\})(ch|deg|dpcm|cm|dpi|dppx|em|ex|grad|in|kHz|Hz|mm|ms|pc|pt|px|rad|rem|s|turn|vh|vmin|vw)\b|%</string>
			<key>name</key>
			<string>keyword.other.unit.css</string>
		</dict>
		<key>variable</key>
		<dict>
			<key>match</key>
			<string>(\$[\w_-]+)</string>
			<key>name</key>
			<string>variable.scss</string>
		</dict>
		<key>variable-declaration</key>
		<dict>
			<key>begin</key>
			<string>\s*(\$[\w_-]+)\s*(:)\s*</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.scss</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.key-value.scss</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=&lt;/style&gt;)|\s*(;)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.terminator.rule.scss</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.variable-declaration.scss</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#variable</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#property-values</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\!\s*default</string>
					<key>name</key>
					<string>keyword.other.default.scss</string>
				</dict>
			</array>
		</dict>
		<key>variables</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#variable</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#interpolation</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.scss</string>
	<key>uuid</key>
	<string>524BB7F2-3C1B-4BD8-AD32-CFC43978B02D</string>
</dict>
</plist>
